export const uiText = {
  en: {
    sidebar: {
      dashboard: 'Dashboard',
      inquiries: 'Price Inquiries',
      orders: 'Orders',
      products: 'Products',
      settings: 'Settings',
      backToSite: 'Back to Site'
    },
    header: {
      admin: 'Admin',
      logout: 'Logout'
    },
    orders: {
      title: 'Order Management',
      total: 'Total Orders',
      pending: 'Pending',
      processing: 'Processing',
      shipped: 'Shipped',
      orderId: 'Order ID',
      customer: 'Customer',
      items: 'Items',
      total: 'Total',
      status: 'Status',
      date: 'Date',
      actions: 'Actions',
      updateStatus: 'Update Status',
      viewDetails: 'View Details',
      statuses: {
        pending: 'Pending Payment',
        paid: 'Paid',
        shipped: 'Shipped',
        delivered: 'Delivered'
      },
      statusMessages: {
        pending: 'Your order has been received. Please complete the payment to proceed.',
        paid: 'Payment confirmed! We are now preparing your order.',
        shipped: 'Your order has been shipped! Tracking number: {tracking}',
        delivered: 'Your order has been delivered. Thank you for your business!'
      },
      trackingNumber: 'Tracking Number',
      trackingPlaceholder: 'Enter tracking number',
      sendNotification: 'Send Notification',
      notificationSent: 'Notification sent to customer',
      customer: 'Customer',
      shippingAddress: 'Shipping Address',
      items: 'Items',
      totalLabel: 'Total',
      orderTimeline: 'Order Timeline',
      trackingAlert: 'Please enter tracking number',
      itemsCount: 'items'
    },
    products: {
      title: 'Products',
      addNew: 'Add New Product',
      status: 'Status',
      product: 'Product',
      category: 'Category',
      moq: 'MOQ',
      updated: 'Last Updated',
      actions: 'Actions',
      active: 'Active',
      inactive: 'Inactive',
      edit: 'Edit',
      delete: 'Delete',
      deleteConfirm: 'This product will no longer be available for inquiries. Are you sure you want to delete it?',
      cancel: 'Cancel'
    },
    productForm: {
      addTitle: 'Add New Product',
      editTitle: 'Edit Product',
      backToList: 'Back to Product List',
      basicInfo: 'Basic Information',
      basicInfoDesc: 'Core product details for identification and categorization.',
      productId: 'Product ID',
      productIdPlaceholder: 'BL-SK-001',
      productIdHelp: 'This Product ID will be used for chatbot inquiries and SNS references.',
      productIdDuplicate: 'This Product ID already exists.',
      nameEn: 'Product Name (EN)',
      nameKr: 'Product Name (KR)',
      category: 'Category',
      llmBasic: 'Basic Response Information',
      llmBasicDesc: 'This information will be used by the chatbot to respond to buyer questions.',
      description: 'Short Product Description',
      ingredients: 'Key Ingredients',
      usage: 'Usage / Texture / Finish',
      usagePlaceholder: 'How to use, texture description, finish type...',
      llmExport: 'Distribution & Export Information',
      exportReady: 'Export Availability',
      certifications: 'Export Certifications',
      certificationsPlaceholder: 'CPNP (EU), FDA Registered, Vegan Certified...',
      moq: 'MOQ Information',
      markets: 'Available Regions',
      llmPrice: 'Price Inquiry Response Settings',
      pricePolicy: 'Price Disclosure Policy',
      pricePolicyValue: 'Hidden (Redirect to inquiry)',
      priceResponse: 'Auto-response Message for Price Inquiries',
      priceResponseDefault: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
      media: 'Product Media',
      mediaDesc: 'These media assets may be referenced during buyer inquiries.',
      mediaImages: 'Product Images',
      mediaDragDrop: 'Drag & drop images here, or click to browse',
      mediaVideo: 'Product Video URL (Optional)',
      mediaVideoPlaceholder: 'https://youtube.com/...',
      mediaWarning: 'Avoid uploading images that display price information.',
      chatbotNote: 'This product will be searchable via chatbot by Product ID or Name.',
      save: 'Save Product',
      cancel: 'Cancel',
      yes: 'Yes',
      no: 'No'
    },
    settings: {
      title: 'Settings',
      adminAccount: 'Admin Account',
      adminName: 'Admin Name',
      adminEmail: 'Admin Email',
      inquirySettings: 'Inquiry Settings',
      defaultResponse: 'Default Price Inquiry Response',
      contactMethods: 'Contact Methods',
      whatsapp: 'WhatsApp',
      email: 'Email',
      language: 'Language Settings',
      defaultLang: 'Default Language',
      save: 'Save Settings',
      saved: 'Settings Saved!'
    },
    detail: {
      conversation: 'Conversation Log',
      priceInquiry: 'Price inquiry received',
      contactInfo: 'Contact Information',
      copy: 'Copy',
      copied: 'Copied!',
      markAs: 'Mark as',
      back: 'Back to List'
    }
  },
  ko: {
    sidebar: {
      dashboard: '대시보드',
      inquiries: '가격 문의',
      orders: '주문 관리',
      products: '제품 관리',
      settings: '설정',
      backToSite: '사이트로 돌아가기'
    },
    header: {
      admin: '관리자',
      logout: '로그아웃'
    },
    orders: {
      title: '주문 관리',
      total: '전체 주문',
      pending: '대기',
      processing: '처리중',
      shipped: '배송중',
      orderId: '주문번호',
      customer: '고객',
      items: '상품',
      total: '합계',
      status: '상태',
      date: '날짜',
      actions: '관리',
      updateStatus: '상태 변경',
      viewDetails: '상세 보기',
      statuses: {
        pending: '결제 대기',
        paid: '결제 완료',
        shipped: '배송 중',
        delivered: '배송 완료'
      },
      statusMessages: {
        pending: '주문이 접수되었습니다. 결제를 완료해주세요.',
        paid: '결제가 확인되었습니다! 주문을 준비하고 있습니다.',
        shipped: '주문이 발송되었습니다! 운송장 번호: {tracking}',
        delivered: '배송이 완료되었습니다. 이용해 주셔서 감사합니다!'
      },
      trackingNumber: '운송장 번호',
      trackingPlaceholder: '운송장 번호 입력',
      sendNotification: '알림 발송',
      notificationSent: '고객에게 알림이 발송되었습니다',
      customer: '고객 정보',
      shippingAddress: '배송지 주소',
      items: '주문 상품',
      totalLabel: '합계',
      orderTimeline: '주문 타임라인',
      trackingAlert: '운송장 번호를 입력해주세요',
      itemsCount: '개 상품'
    },
    products: {
      title: '제품 관리',
      addNew: '새 제품 등록',
      status: '상태',
      product: '제품',
      category: '카테고리',
      moq: 'MOQ',
      updated: '최근 수정',
      actions: '관리',
      active: '활성',
      inactive: '비활성',
      edit: '수정',
      delete: '삭제',
      deleteConfirm: '이 제품은 더 이상 문의에 사용할 수 없게 됩니다. 정말 삭제하시겠습니까?',
      cancel: '취소'
    },
    productForm: {
      addTitle: '새 제품 등록',
      editTitle: '제품 수정',
      backToList: '제품 목록으로',
      basicInfo: '기본 정보',
      basicInfoDesc: '제품 식별 및 분류를 위한 핵심 정보입니다.',
      productId: '제품 고유 번호',
      productIdPlaceholder: 'BL-SK-001',
      productIdHelp: '이 제품 번호는 챗봇 문의 및 SNS 참조에 사용됩니다.',
      productIdDuplicate: '이미 존재하는 제품 번호입니다.',
      nameEn: '제품명 (영문)',
      nameKr: '제품명 (한글)',
      category: '카테고리',
      llmBasic: '기본 응대 정보',
      llmBasicDesc: '이 정보는 챗봇이 바이어 질문에 응답할 때 사용됩니다.',
      description: '짧은 제품 설명',
      ingredients: '주요 성분',
      usage: '사용법 / 텍스처 / 피니시',
      usagePlaceholder: '사용 방법, 질감 설명, 마무리감...',
      llmExport: '유통 & 수출 정보',
      exportReady: '수출 가능 여부',
      certifications: '수출 인증',
      certificationsPlaceholder: 'CPNP (EU), FDA Registered, Vegan Certified...',
      moq: 'MOQ 정보',
      markets: '판매 가능 지역',
      llmPrice: '가격 문의 응대 설정',
      pricePolicy: '가격 공개 정책',
      pricePolicyValue: '비공개 (문의로 전환)',
      priceResponse: '가격 문의 시 자동 응답 문구',
      priceResponseDefault: '관심을 가져주셔서 감사합니다. 정확한 가격 정보는 담당팀에서 곧 연락드리겠습니다.',
      media: '제품 미디어',
      mediaDesc: '이 미디어 자료는 바이어 문의 시 참조될 수 있습니다.',
      mediaImages: '제품 이미지',
      mediaDragDrop: '이미지를 드래그하거나 클릭하여 업로드',
      mediaVideo: '제품 영상 URL (선택)',
      mediaVideoPlaceholder: 'https://youtube.com/...',
      mediaWarning: '가격 정보가 표시된 이미지 업로드는 피해주세요.',
      chatbotNote: '이 제품은 제품 번호 또는 이름으로 챗봇 검색이 가능합니다.',
      save: '저장',
      cancel: '취소',
      yes: '예',
      no: '아니오'
    },
    settings: {
      title: '설정',
      adminAccount: '관리자 계정',
      adminName: '관리자 이름',
      adminEmail: '관리자 이메일',
      inquirySettings: '문의 설정',
      defaultResponse: '가격 문의 기본 응답 문구',
      contactMethods: '연락 방법',
      whatsapp: 'WhatsApp',
      email: '이메일',
      language: '언어 설정',
      defaultLang: '기본 언어',
      save: '설정 저장',
      saved: '저장되었습니다!'
    },
    detail: {
      conversation: '대화 기록',
      priceInquiry: '가격 문의 발생',
      contactInfo: '연락처 정보',
      copy: '복사',
      copied: '복사됨!',
      markAs: '상태 변경',
      back: '목록으로'
    }
  }
}
