export const initialProducts = [
  {
    id: 1,
    productId: 'BL-SK-001',
    productCode: 'BL-SK-001',
    nameEn: 'Hydra Glow Serum',
    nameKr: '하이드라 글로우 세럼',
    productName: 'Hydra Glow Serum',
    brandName: 'Young Cosmed',
    category: 'Skincare',
    image: '/product1.png',
    status: 'active',
    description: 'A lightweight hydrating serum formulated with hyaluronic acid and niacinamide for deep moisture and radiant skin.\n\n[Key Ingredients]\nHyaluronic Acid, Niacinamide, Centella Asiatica Extract, Panthenol\n\n[Usage]\nApply 2-3 drops after cleansing. Pat gently for absorption.',
    ingredients: 'Hyaluronic Acid, Niacinamide, Centella Asiatica Extract, Panthenol',
    usage: 'Apply 2-3 drops after cleansing. Pat gently for absorption.',
    exportReady: true,
    certifications: ['CPNP (EU)', 'FDA'],
    moq: '500',
    shelfLife: '36 months',
    requiresLicense: false,
    markets: 'EU, US, ASIA',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product1.png'],
    mainImage: null,
    additionalImages: [],
    mediaVideo: '',
    updatedAt: '2024-02-10T09:00:00Z',
    pricing: {
      basePrice: 15,
      moqDiscountTiers: [
        { minQty: 1000, discount: 0.05 },
        { minQty: 5000, discount: 0.10 },
        { minQty: 10000, discount: 0.15 }
      ],
      countryPricing: {
        'USA': { enabled: true, unitPrice: null, shipping: 150, tariff: 0.025 },
        'Japan': { enabled: true, unitPrice: null, shipping: 80, tariff: 0.05 },
        'South Korea': { enabled: true, unitPrice: null, shipping: 50, tariff: 0 },
        'China': { enabled: true, unitPrice: null, shipping: 70, tariff: 0.06 },
        'UK': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Germany': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'France': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Australia': { enabled: true, unitPrice: null, shipping: 130, tariff: 0.05 },
        'Canada': { enabled: true, unitPrice: null, shipping: 120, tariff: 0.03 },
        'Singapore': { enabled: true, unitPrice: null, shipping: 90, tariff: 0 },
        'UAE': { enabled: true, unitPrice: null, shipping: 160, tariff: 0.05 }
      }
    }
  },
  {
    id: 2,
    productId: 'BL-MK-001',
    productCode: 'BL-MK-001',
    nameEn: 'Velvet Matte Lip Tint',
    nameKr: '벨벳 매트 립틴트',
    productName: 'Velvet Matte Lip Tint',
    brandName: 'Young Cosmed',
    category: 'Makeup',
    image: '/product2.png',
    status: 'active',
    description: 'Long-lasting velvet matte finish lip tint with intense color payoff and comfortable wear.\n\n[Key Ingredients]\nJojoba Oil, Vitamin E, Natural Pigments\n\n[Usage]\nApply directly to lips. Build up for more intense color.',
    ingredients: 'Jojoba Oil, Vitamin E, Natural Pigments',
    usage: 'Apply directly to lips. Build up for more intense color.',
    exportReady: true,
    certifications: ['CPNP (EU)', 'FDA'],
    moq: '300',
    shelfLife: '24 months',
    requiresLicense: false,
    markets: 'Global',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product2.png'],
    mainImage: null,
    additionalImages: [],
    mediaVideo: '',
    updatedAt: '2024-02-09T15:00:00Z',
    pricing: {
      basePrice: 8,
      moqDiscountTiers: [
        { minQty: 1000, discount: 0.05 },
        { minQty: 5000, discount: 0.10 },
        { minQty: 10000, discount: 0.15 }
      ],
      countryPricing: {
        'USA': { enabled: true, unitPrice: null, shipping: 150, tariff: 0.025 },
        'Japan': { enabled: true, unitPrice: null, shipping: 80, tariff: 0.05 },
        'South Korea': { enabled: true, unitPrice: null, shipping: 50, tariff: 0 },
        'China': { enabled: true, unitPrice: null, shipping: 70, tariff: 0.06 },
        'UK': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Germany': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'France': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Australia': { enabled: true, unitPrice: null, shipping: 130, tariff: 0.05 },
        'Canada': { enabled: true, unitPrice: null, shipping: 120, tariff: 0.03 },
        'Singapore': { enabled: true, unitPrice: null, shipping: 90, tariff: 0 },
        'UAE': { enabled: true, unitPrice: null, shipping: 160, tariff: 0.05 }
      }
    }
  },
  {
    id: 3,
    productId: 'BL-SK-002',
    productCode: 'BL-SK-002',
    nameEn: 'Cica Repair Cream',
    nameKr: '시카 리페어 크림',
    productName: 'Cica Repair Cream',
    brandName: 'Young Cosmed',
    category: 'Skincare',
    image: '/product3.png',
    status: 'active',
    description: 'Intensive repair cream with Centella Asiatica for sensitive and damaged skin barrier restoration.\n\n[Key Ingredients]\nCentella Asiatica, Madecassoside, Ceramide NP, Beta-Glucan\n\n[Usage]\nApply generously to face and neck as the last step of skincare.',
    ingredients: 'Centella Asiatica, Madecassoside, Ceramide NP, Beta-Glucan',
    usage: 'Apply generously to face and neck as the last step of skincare.',
    exportReady: true,
    certifications: ['CPNP (EU)', 'FDA', 'Vegan'],
    moq: '400',
    shelfLife: '36 months',
    requiresLicense: false,
    markets: 'EU, ASIA',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product3.png'],
    mainImage: null,
    additionalImages: [],
    mediaVideo: '',
    updatedAt: '2024-02-08T10:00:00Z',
    pricing: {
      basePrice: 12,
      moqDiscountTiers: [
        { minQty: 1000, discount: 0.05 },
        { minQty: 5000, discount: 0.10 },
        { minQty: 10000, discount: 0.15 }
      ],
      countryPricing: {
        'USA': { enabled: true, unitPrice: null, shipping: 150, tariff: 0.025 },
        'Japan': { enabled: true, unitPrice: null, shipping: 80, tariff: 0.05 },
        'South Korea': { enabled: true, unitPrice: null, shipping: 50, tariff: 0 },
        'China': { enabled: true, unitPrice: null, shipping: 70, tariff: 0.06 },
        'UK': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Germany': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'France': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Australia': { enabled: true, unitPrice: null, shipping: 130, tariff: 0.05 },
        'Canada': { enabled: true, unitPrice: null, shipping: 120, tariff: 0.03 },
        'Singapore': { enabled: true, unitPrice: null, shipping: 90, tariff: 0 },
        'UAE': { enabled: true, unitPrice: null, shipping: 160, tariff: 0.05 }
      }
    }
  },
  {
    id: 4,
    productId: 'BL-CL-001',
    productCode: 'BL-CL-001',
    nameEn: 'Double Cleansing Oil',
    nameKr: '더블 클렌징 오일',
    productName: 'Double Cleansing Oil',
    brandName: 'Young Cosmed',
    category: 'Cleansing',
    image: '/product4.png',
    status: 'active',
    description: 'Gentle yet effective cleansing oil that removes makeup and impurities without stripping moisture.\n\n[Key Ingredients]\nJojoba Seed Oil, Olive Oil, Grape Seed Oil, Vitamin E\n\n[Usage]\nMassage onto dry face, emulsify with water, then rinse.',
    ingredients: 'Jojoba Seed Oil, Olive Oil, Grape Seed Oil, Vitamin E',
    usage: 'Massage onto dry face, emulsify with water, then rinse.',
    exportReady: true,
    certifications: ['CPNP (EU)', 'FDA'],
    moq: '600',
    shelfLife: '30 months',
    requiresLicense: false,
    markets: 'Global',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product4.png'],
    mainImage: null,
    additionalImages: [],
    mediaVideo: '',
    updatedAt: '2024-02-07T14:00:00Z',
    pricing: {
      basePrice: 10,
      moqDiscountTiers: [
        { minQty: 1000, discount: 0.05 },
        { minQty: 5000, discount: 0.10 },
        { minQty: 10000, discount: 0.15 }
      ],
      countryPricing: {
        'USA': { enabled: true, unitPrice: null, shipping: 150, tariff: 0.025 },
        'Japan': { enabled: true, unitPrice: null, shipping: 80, tariff: 0.05 },
        'South Korea': { enabled: true, unitPrice: null, shipping: 50, tariff: 0 },
        'China': { enabled: true, unitPrice: null, shipping: 70, tariff: 0.06 },
        'UK': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Germany': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'France': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Australia': { enabled: true, unitPrice: null, shipping: 130, tariff: 0.05 },
        'Canada': { enabled: true, unitPrice: null, shipping: 120, tariff: 0.03 },
        'Singapore': { enabled: true, unitPrice: null, shipping: 90, tariff: 0 },
        'UAE': { enabled: true, unitPrice: null, shipping: 160, tariff: 0.05 }
      }
    }
  },
  {
    id: 5,
    productId: 'BL-SK-003',
    productCode: 'BL-SK-003',
    nameEn: 'Peptide Eye Contour',
    nameKr: '펩타이드 아이 컨투어',
    productName: 'Peptide Eye Contour',
    brandName: 'Young Cosmed',
    category: 'Skincare',
    image: '/product5.png',
    status: 'active',
    description: 'Advanced eye cream with peptide complex targeting fine lines, dark circles, and puffiness.\n\n[Key Ingredients]\nAcetyl Hexapeptide-8, Caffeine, Adenosine, Squalane\n\n[Usage]\nGently pat around eye area morning and night.',
    ingredients: 'Acetyl Hexapeptide-8, Caffeine, Adenosine, Squalane',
    usage: 'Gently pat around eye area morning and night.',
    exportReady: true,
    certifications: ['CPNP (EU)', 'FDA'],
    moq: '350',
    shelfLife: '24 months',
    requiresLicense: false,
    markets: 'US, EU',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product5.png'],
    mainImage: null,
    additionalImages: [],
    mediaVideo: '',
    updatedAt: '2024-02-06T11:00:00Z',
    pricing: {
      basePrice: 18,
      moqDiscountTiers: [
        { minQty: 1000, discount: 0.05 },
        { minQty: 5000, discount: 0.10 },
        { minQty: 10000, discount: 0.15 }
      ],
      countryPricing: {
        'USA': { enabled: true, unitPrice: null, shipping: 150, tariff: 0.025 },
        'Japan': { enabled: true, unitPrice: null, shipping: 80, tariff: 0.05 },
        'South Korea': { enabled: true, unitPrice: null, shipping: 50, tariff: 0 },
        'China': { enabled: true, unitPrice: null, shipping: 70, tariff: 0.06 },
        'UK': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Germany': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'France': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Australia': { enabled: true, unitPrice: null, shipping: 130, tariff: 0.05 },
        'Canada': { enabled: true, unitPrice: null, shipping: 120, tariff: 0.03 },
        'Singapore': { enabled: true, unitPrice: null, shipping: 90, tariff: 0 },
        'UAE': { enabled: true, unitPrice: null, shipping: 160, tariff: 0.05 }
      }
    }
  },
  {
    id: 6,
    productId: 'BL-SN-001',
    productCode: 'BL-SN-001',
    nameEn: 'Tone-Up Sun Shield',
    nameKr: '톤업 선쉴드',
    productName: 'Tone-Up Sun Shield',
    brandName: 'Young Cosmed',
    category: 'Sun Care',
    image: '/product6.png',
    status: 'active',
    description: 'Lightweight SPF50+ PA++++ sunscreen with tone-up effect for natural, protected skin.\n\n[Key Ingredients]\nZinc Oxide, Niacinamide, Centella Asiatica, Hyaluronic Acid\n\n[Usage]\nApply as last step of morning skincare. Reapply every 2-3 hours.',
    ingredients: 'Zinc Oxide, Niacinamide, Centella Asiatica, Hyaluronic Acid',
    usage: 'Apply as last step of morning skincare. Reapply every 2-3 hours.',
    exportReady: true,
    certifications: ['CPNP (EU)', 'FDA'],
    moq: '500',
    shelfLife: '30 months',
    requiresLicense: false,
    markets: 'Global',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product6.png'],
    mainImage: null,
    additionalImages: [],
    mediaVideo: '',
    updatedAt: '2024-02-05T09:00:00Z',
    pricing: {
      basePrice: 11,
      moqDiscountTiers: [
        { minQty: 1000, discount: 0.05 },
        { minQty: 5000, discount: 0.10 },
        { minQty: 10000, discount: 0.15 }
      ],
      countryPricing: {
        'USA': { enabled: true, unitPrice: null, shipping: 150, tariff: 0.025 },
        'Japan': { enabled: true, unitPrice: null, shipping: 80, tariff: 0.05 },
        'South Korea': { enabled: true, unitPrice: null, shipping: 50, tariff: 0 },
        'China': { enabled: true, unitPrice: null, shipping: 70, tariff: 0.06 },
        'UK': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Germany': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'France': { enabled: true, unitPrice: null, shipping: 140, tariff: 0.02 },
        'Australia': { enabled: true, unitPrice: null, shipping: 130, tariff: 0.05 },
        'Canada': { enabled: true, unitPrice: null, shipping: 120, tariff: 0.03 },
        'Singapore': { enabled: true, unitPrice: null, shipping: 90, tariff: 0 },
        'UAE': { enabled: true, unitPrice: null, shipping: 160, tariff: 0.05 }
      }
    }
  },
]
