export const initialProducts = [
  {
    id: 1,
    productId: 'BL-SK-001',
    nameEn: 'Hydra Glow Serum',
    nameKr: '하이드라 글로우 세럼',
    category: 'Skincare',
    image: '/product1.png',
    status: 'active',
    description: 'A lightweight hydrating serum formulated with hyaluronic acid and niacinamide for deep moisture and radiant skin.',
    ingredients: 'Hyaluronic Acid, Niacinamide, Centella Asiatica Extract, Panthenol',
    usage: 'Apply 2-3 drops after cleansing. Pat gently for absorption.',
    exportReady: true,
    certifications: 'CPNP (EU), FDA Registered',
    moq: '500 units',
    markets: 'EU, US, ASIA',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product1.png'],
    mediaVideo: '',
    updatedAt: '2024-02-10T09:00:00Z'
  },
  {
    id: 2,
    productId: 'BL-MK-001',
    nameEn: 'Velvet Matte Lip Tint',
    nameKr: '벨벳 매트 립틴트',
    category: 'Makeup',
    image: '/product2.png',
    status: 'active',
    description: 'Long-lasting velvet matte finish lip tint with intense color payoff and comfortable wear.',
    ingredients: 'Jojoba Oil, Vitamin E, Natural Pigments',
    usage: 'Apply directly to lips. Build up for more intense color.',
    exportReady: true,
    certifications: 'CPNP (EU), FDA Registered',
    moq: '300 units',
    markets: 'Global',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product2.png'],
    mediaVideo: '',
    updatedAt: '2024-02-09T15:00:00Z'
  },
  {
    id: 3,
    productId: 'BL-SK-002',
    nameEn: 'Cica Repair Cream',
    nameKr: '시카 리페어 크림',
    category: 'Skincare',
    image: '/product3.png',
    status: 'active',
    description: 'Intensive repair cream with Centella Asiatica for sensitive and damaged skin barrier restoration.',
    ingredients: 'Centella Asiatica, Madecassoside, Ceramide NP, Beta-Glucan',
    usage: 'Apply generously to face and neck as the last step of skincare.',
    exportReady: true,
    certifications: 'CPNP (EU), FDA Registered, Vegan Certified',
    moq: '400 units',
    markets: 'EU, ASIA',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product3.png'],
    mediaVideo: '',
    updatedAt: '2024-02-08T10:00:00Z'
  },
  {
    id: 4,
    productId: 'BL-CL-001',
    nameEn: 'Double Cleansing Oil',
    nameKr: '더블 클렌징 오일',
    category: 'Cleansing',
    image: '/product4.png',
    status: 'active',
    description: 'Gentle yet effective cleansing oil that removes makeup and impurities without stripping moisture.',
    ingredients: 'Jojoba Seed Oil, Olive Oil, Grape Seed Oil, Vitamin E',
    usage: 'Massage onto dry face, emulsify with water, then rinse.',
    exportReady: true,
    certifications: 'CPNP (EU), FDA Registered',
    moq: '600 units',
    markets: 'Global',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product4.png'],
    mediaVideo: '',
    updatedAt: '2024-02-07T14:00:00Z'
  },
  {
    id: 5,
    productId: 'BL-SK-003',
    nameEn: 'Peptide Eye Contour',
    nameKr: '펩타이드 아이 컨투어',
    category: 'Skincare',
    image: '/product5.png',
    status: 'active',
    description: 'Advanced eye cream with peptide complex targeting fine lines, dark circles, and puffiness.',
    ingredients: 'Acetyl Hexapeptide-8, Caffeine, Adenosine, Squalane',
    usage: 'Gently pat around eye area morning and night.',
    exportReady: true,
    certifications: 'CPNP (EU), FDA Registered',
    moq: '350 units',
    markets: 'US, EU',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product5.png'],
    mediaVideo: '',
    updatedAt: '2024-02-06T11:00:00Z'
  },
  {
    id: 6,
    productId: 'BL-SN-001',
    nameEn: 'Tone-Up Sun Shield',
    nameKr: '톤업 선쉴드',
    category: 'Sun Care',
    image: '/product6.png',
    status: 'active',
    description: 'Lightweight SPF50+ PA++++ sunscreen with tone-up effect for natural, protected skin.',
    ingredients: 'Zinc Oxide, Niacinamide, Centella Asiatica, Hyaluronic Acid',
    usage: 'Apply as last step of morning skincare. Reapply every 2-3 hours.',
    exportReady: true,
    certifications: 'CPNP (EU), FDA Registered',
    moq: '500 units',
    markets: 'Global',
    priceResponse: 'Thank you for your interest. For accurate pricing, our Sales Team will contact you shortly.',
    mediaImages: ['/product6.png'],
    mediaVideo: '',
    updatedAt: '2024-02-05T09:00:00Z'
  },
]
